spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/sistemavuelossb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=

spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=9000